version: "3"
services: 
  gitea:
    image: gitea/gitea:1.8.3
    ports:
      - "10080:3000"
      - "10022:22"
    volumes: 
      - gitea:/data
    restart: always
    environment: 
      - USER_UID=1000
      - USER_GID=1000

  drone-server:
    image: drone/drone:1.1.0
    ports:
      - 8000:80
    volumes:
      - drone:/data
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}
      - DRONE_TLS_AUTOCERT=false
      - DRONE_GIT_ALWAYS_AUTH=true
      - DRONE_GITEA_SERVER=${DRONE_GITEA_SERVER}
      - DRONE_AGENTS_ENABLED=true
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_LOGS_DEBUG=true
      - DRONE_USER_CREATE=username:${DRONE_ADMIN},admin:true
      - DRONE_GITEA_CLIENT_ID=${DRONE_GITEA_CLIENT_ID}
      - DRONE_GITEA_CLIENT_SECRET=${DRONE_GITEA_CLIENT_SECRET}

  drone-agent:
    image: drone/agent:1.1.0
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_SERVER=${DRONE_RPC_SERVER}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_LOGS_DEBUG=true

volumes:
  drone:
  gitea:
