version: "3"
services: 
  gitea:
    image: gitea/gitea:1.8.3
    ports:
      - "10080:3000"
      - "10022:22"
    volumes: 
      - gitea:/data
    restart: always
    environment: 
      - USER_UID=1000
      - USER_GID=1000

volumes:
  gitea:
