version: "3.7"
services:
  server:
    image: drone/drone:1.2.1
    networks:
      - gitdrone
    ports:
      - "8000:80"
    configs:
      - source: drone-server-env
        target: /.env
    volumes:
      - drone:/data
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  agent:
    image: drone/agent:1.2.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitdrone
    configs:
      - source: drone-agent-env
        target: /.env
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 20s

  gitea-server:
    image: gitea/gitea:1.8.3
    environment:
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - "10080:3000"
      - "10022:22"
    networks:
      - gitdrone
    volumes:
      - gitea:/data
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 20s

networks:
  gitdrone:

volumes:
  drone:
  gitea:

configs:
  drone-server-env:
    file: ./server-env
  drone-agent-env:
    file: ./agent-env
